// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class OrderResponseData;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - OrderRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface OrderRoot : GPBRootObject
@end

#pragma mark - OrderRequest

typedef GPB_ENUM(OrderRequest_FieldNumber) {
  OrderRequest_FieldNumber_PutSymbol = 1,
  OrderRequest_FieldNumber_Cmd = 2,
  OrderRequest_FieldNumber_Price = 3,
  OrderRequest_FieldNumber_Volume = 4,
  OrderRequest_FieldNumber_Sl = 5,
  OrderRequest_FieldNumber_Tp = 6,
  OrderRequest_FieldNumber_Deviation = 7,
  OrderRequest_FieldNumber_Comment = 8,
  OrderRequest_FieldNumber_UserToken = 9,
  OrderRequest_FieldNumber_Rand = 10,
  OrderRequest_FieldNumber_Time = 11,
  OrderRequest_FieldNumber_SessionId = 12,
  OrderRequest_FieldNumber_Language = 13,
};

@interface OrderRequest : GPBMessage

/** 交易产品编号 llg 伦敦金 lls 伦敦银 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *putSymbol;
/** Test to see if @c putSymbol has been set. */
@property(nonatomic, readwrite) BOOL hasPutSymbol;

/** 交易方向  0做多 1做空 */
@property(nonatomic, readwrite) int32_t cmd;

@property(nonatomic, readwrite) BOOL hasCmd;
/** 建仓价格 */
@property(nonatomic, readwrite) float price;

@property(nonatomic, readwrite) BOOL hasPrice;
/** 交易手数 */
@property(nonatomic, readwrite) float volume;

@property(nonatomic, readwrite) BOOL hasVolume;
/** 止损 */
@property(nonatomic, readwrite) float sl;

@property(nonatomic, readwrite) BOOL hasSl;
/** 止盈 */
@property(nonatomic, readwrite) float tp;

@property(nonatomic, readwrite) BOOL hasTp;
/** 滑点 */
@property(nonatomic, readwrite) float deviation;

@property(nonatomic, readwrite) BOOL hasDeviation;
/** 说明 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *comment;
/** Test to see if @c comment has been set. */
@property(nonatomic, readwrite) BOOL hasComment;

/** 用户标识 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userToken;
/** Test to see if @c userToken has been set. */
@property(nonatomic, readwrite) BOOL hasUserToken;

@property(nonatomic, readwrite) int32_t rand;

@property(nonatomic, readwrite) BOOL hasRand;
@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) BOOL hasTime;
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *language;
/** Test to see if @c language has been set. */
@property(nonatomic, readwrite) BOOL hasLanguage;

@end

#pragma mark - OrderResponse

typedef GPB_ENUM(OrderResponse_FieldNumber) {
  OrderResponse_FieldNumber_Success = 1,
  OrderResponse_FieldNumber_ErrCode = 2,
  OrderResponse_FieldNumber_Message = 3,
  OrderResponse_FieldNumber_Value = 4,
  OrderResponse_FieldNumber_SessionId = 5,
};

@interface OrderResponse : GPBMessage

@property(nonatomic, readwrite) int32_t success;

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite) int32_t errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@property(nonatomic, readwrite, strong, null_resettable) OrderResponseData *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@end

#pragma mark - OrderResponseData

typedef GPB_ENUM(OrderResponseData_FieldNumber) {
  OrderResponseData_FieldNumber_Ask = 4,
  OrderResponseData_FieldNumber_Bid = 5,
  OrderResponseData_FieldNumber_Order = 6,
};

@interface OrderResponseData : GPBMessage

@property(nonatomic, readwrite) float ask;

@property(nonatomic, readwrite) BOOL hasAsk;
@property(nonatomic, readwrite) float bid;

@property(nonatomic, readwrite) BOOL hasBid;
@property(nonatomic, readwrite) int64_t order;

@property(nonatomic, readwrite) BOOL hasOrder;
@end

#pragma mark - CloseRequest

typedef GPB_ENUM(CloseRequest_FieldNumber) {
  CloseRequest_FieldNumber_Ticket = 1,
  CloseRequest_FieldNumber_Price = 2,
  CloseRequest_FieldNumber_Volume = 3,
  CloseRequest_FieldNumber_UserToken = 4,
  CloseRequest_FieldNumber_Rand = 5,
  CloseRequest_FieldNumber_Time = 6,
  CloseRequest_FieldNumber_SessionId = 7,
  CloseRequest_FieldNumber_Language = 8,
  CloseRequest_FieldNumber_HoldVolume = 9,
};

@interface CloseRequest : GPBMessage

/** 交易产品编号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ticket;
/** Test to see if @c ticket has been set. */
@property(nonatomic, readwrite) BOOL hasTicket;

/** 平仓价格 */
@property(nonatomic, readwrite) float price;

@property(nonatomic, readwrite) BOOL hasPrice;
/** 交易手数 */
@property(nonatomic, readwrite) float volume;

@property(nonatomic, readwrite) BOOL hasVolume;
/** 用户标识 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userToken;
/** Test to see if @c userToken has been set. */
@property(nonatomic, readwrite) BOOL hasUserToken;

@property(nonatomic, readwrite) int32_t rand;

@property(nonatomic, readwrite) BOOL hasRand;
@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) BOOL hasTime;
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *language;
/** Test to see if @c language has been set. */
@property(nonatomic, readwrite) BOOL hasLanguage;

/** 手数 */
@property(nonatomic, readwrite) float holdVolume;

@property(nonatomic, readwrite) BOOL hasHoldVolume;
@end

#pragma mark - CloseResponse

typedef GPB_ENUM(CloseResponse_FieldNumber) {
  CloseResponse_FieldNumber_Success = 1,
  CloseResponse_FieldNumber_ErrCode = 2,
  CloseResponse_FieldNumber_Message = 3,
  CloseResponse_FieldNumber_SessionId = 4,
};

@interface CloseResponse : GPBMessage

@property(nonatomic, readwrite) int32_t success;

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite) int32_t errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@end

#pragma mark - CancelRequest

typedef GPB_ENUM(CancelRequest_FieldNumber) {
  CancelRequest_FieldNumber_Ticket = 1,
  CancelRequest_FieldNumber_UserToken = 2,
  CancelRequest_FieldNumber_Rand = 3,
  CancelRequest_FieldNumber_Time = 4,
  CancelRequest_FieldNumber_SessionId = 5,
  CancelRequest_FieldNumber_Language = 6,
};

@interface CancelRequest : GPBMessage

/** 交易产品编号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ticket;
/** Test to see if @c ticket has been set. */
@property(nonatomic, readwrite) BOOL hasTicket;

/** 用户标识 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userToken;
/** Test to see if @c userToken has been set. */
@property(nonatomic, readwrite) BOOL hasUserToken;

@property(nonatomic, readwrite) int32_t rand;

@property(nonatomic, readwrite) BOOL hasRand;
@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) BOOL hasTime;
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *language;
/** Test to see if @c language has been set. */
@property(nonatomic, readwrite) BOOL hasLanguage;

@end

#pragma mark - CancelResponse

typedef GPB_ENUM(CancelResponse_FieldNumber) {
  CancelResponse_FieldNumber_Success = 1,
  CancelResponse_FieldNumber_ErrCode = 2,
  CancelResponse_FieldNumber_Message = 3,
  CancelResponse_FieldNumber_SessionId = 4,
};

@interface CancelResponse : GPBMessage

@property(nonatomic, readwrite) int32_t success;

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite) int32_t errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@end

#pragma mark - ModifyRequest

typedef GPB_ENUM(ModifyRequest_FieldNumber) {
  ModifyRequest_FieldNumber_Ticket = 1,
  ModifyRequest_FieldNumber_Tp = 2,
  ModifyRequest_FieldNumber_Sl = 3,
  ModifyRequest_FieldNumber_UserToken = 4,
  ModifyRequest_FieldNumber_Rand = 5,
  ModifyRequest_FieldNumber_Time = 6,
  ModifyRequest_FieldNumber_SessionId = 7,
  ModifyRequest_FieldNumber_Language = 8,
};

@interface ModifyRequest : GPBMessage

/** 交易产品编号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ticket;
/** Test to see if @c ticket has been set. */
@property(nonatomic, readwrite) BOOL hasTicket;

/** 止盈 */
@property(nonatomic, readwrite) float tp;

@property(nonatomic, readwrite) BOOL hasTp;
/** 止损 */
@property(nonatomic, readwrite) float sl;

@property(nonatomic, readwrite) BOOL hasSl;
/** 用户标识 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userToken;
/** Test to see if @c userToken has been set. */
@property(nonatomic, readwrite) BOOL hasUserToken;

@property(nonatomic, readwrite) int32_t rand;

@property(nonatomic, readwrite) BOOL hasRand;
@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) BOOL hasTime;
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *language;
/** Test to see if @c language has been set. */
@property(nonatomic, readwrite) BOOL hasLanguage;

@end

#pragma mark - ModifyResponse

typedef GPB_ENUM(ModifyResponse_FieldNumber) {
  ModifyResponse_FieldNumber_Success = 1,
  ModifyResponse_FieldNumber_ErrCode = 2,
  ModifyResponse_FieldNumber_Message = 3,
  ModifyResponse_FieldNumber_SessionId = 4,
};

@interface ModifyResponse : GPBMessage

@property(nonatomic, readwrite) int32_t success;

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite) int32_t errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
