// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tradingaccount.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class TradingAccountData;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TradingaccountRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface TradingaccountRoot : GPBRootObject
@end

#pragma mark - TradingAccountRequest

typedef GPB_ENUM(TradingAccountRequest_FieldNumber) {
  TradingAccountRequest_FieldNumber_UserToken = 1,
  TradingAccountRequest_FieldNumber_SessionId = 2,
  TradingAccountRequest_FieldNumber_Language = 3,
};

@interface TradingAccountRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

/** 用户标识 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userToken;
/** Test to see if @c userToken has been set. */
@property(nonatomic, readwrite) BOOL hasUserToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *language;
/** Test to see if @c language has been set. */
@property(nonatomic, readwrite) BOOL hasLanguage;

@end

#pragma mark - TradingAccountData

typedef GPB_ENUM(TradingAccountData_FieldNumber) {
  TradingAccountData_FieldNumber_PrevMonthBalance = 1,
  TradingAccountData_FieldNumber_Equity = 2,
  TradingAccountData_FieldNumber_Credit = 3,
  TradingAccountData_FieldNumber_MarginLevel = 4,
  TradingAccountData_FieldNumber_Balance = 5,
  TradingAccountData_FieldNumber_Margin = 6,
  TradingAccountData_FieldNumber_Fl = 7,
  TradingAccountData_FieldNumber_MarginFree = 8,
};

@interface TradingAccountData : GPBMessage

/** 可用预付款 */
@property(nonatomic, readwrite) double prevMonthBalance;

@property(nonatomic, readwrite) BOOL hasPrevMonthBalance;
/** 净值 */
@property(nonatomic, readwrite) double equity;

@property(nonatomic, readwrite) BOOL hasEquity;
/** 信用 */
@property(nonatomic, readwrite) double credit;

@property(nonatomic, readwrite) BOOL hasCredit;
/** 风险率 */
@property(nonatomic, readwrite) double marginLevel;

@property(nonatomic, readwrite) BOOL hasMarginLevel;
/** 余额 */
@property(nonatomic, readwrite) double balance;

@property(nonatomic, readwrite) BOOL hasBalance;
/** 已用预付款 */
@property(nonatomic, readwrite) double margin;

@property(nonatomic, readwrite) BOOL hasMargin;
/** 浮动盈亏 */
@property(nonatomic, readwrite) double fl;

@property(nonatomic, readwrite) BOOL hasFl;
/** 可用预付款 */
@property(nonatomic, readwrite) double marginFree;

@property(nonatomic, readwrite) BOOL hasMarginFree;
@end

#pragma mark - TradingAccountResponse

typedef GPB_ENUM(TradingAccountResponse_FieldNumber) {
  TradingAccountResponse_FieldNumber_Success = 1,
  TradingAccountResponse_FieldNumber_ErrCode = 2,
  TradingAccountResponse_FieldNumber_Message = 3,
  TradingAccountResponse_FieldNumber_Value = 4,
  TradingAccountResponse_FieldNumber_SessionId = 5,
};

@interface TradingAccountResponse : GPBMessage

@property(nonatomic, readwrite) int32_t success;

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite) int32_t errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@property(nonatomic, readwrite, strong, null_resettable) TradingAccountData *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
