// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: immessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ImmessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ImmessageRoot : GPBRootObject
@end

#pragma mark - IMMessageRequest

typedef GPB_ENUM(IMMessageRequest_FieldNumber) {
  IMMessageRequest_FieldNumber_UserId = 1,
  IMMessageRequest_FieldNumber_MsgId = 2,
  IMMessageRequest_FieldNumber_Content = 3,
  IMMessageRequest_FieldNumber_To = 4,
  IMMessageRequest_FieldNumber_From = 5,
  IMMessageRequest_FieldNumber_ContentType = 6,
  IMMessageRequest_FieldNumber_Param = 7,
};

@interface IMMessageRequest : GPBMessage

/** 用户标识 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

/** 本地消息编号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;
/** Test to see if @c msgId has been set. */
@property(nonatomic, readwrite) BOOL hasMsgId;

/** 内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

/** 接收方 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;
/** Test to see if @c to has been set. */
@property(nonatomic, readwrite) BOOL hasTo;

/** 发送方 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *from;
/** Test to see if @c from has been set. */
@property(nonatomic, readwrite) BOOL hasFrom;

/** 内容类型 */
@property(nonatomic, readwrite) int32_t contentType;

@property(nonatomic, readwrite) BOOL hasContentType;
/** 扩展字段 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *param;
/** Test to see if @c param has been set. */
@property(nonatomic, readwrite) BOOL hasParam;

@end

#pragma mark - IMMessageResponse

typedef GPB_ENUM(IMMessageResponse_FieldNumber) {
  IMMessageResponse_FieldNumber_Success = 1,
  IMMessageResponse_FieldNumber_MsgId = 2,
};

@interface IMMessageResponse : GPBMessage

@property(nonatomic, readwrite) int32_t success;

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;
/** Test to see if @c msgId has been set. */
@property(nonatomic, readwrite) BOOL hasMsgId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
