// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MessageData;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageRoot : GPBRootObject
@end

#pragma mark - MessageResponse

typedef GPB_ENUM(MessageResponse_FieldNumber) {
  MessageResponse_FieldNumber_Success = 1,
  MessageResponse_FieldNumber_ErrCode = 2,
  MessageResponse_FieldNumber_Type = 3,
  MessageResponse_FieldNumber_Value = 4,
  MessageResponse_FieldNumber_SessionId = 5,
};

@interface MessageResponse : GPBMessage

@property(nonatomic, readwrite) int32_t success;

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite) int32_t errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite, strong, null_resettable) MessageData *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@end

#pragma mark - MessageData

typedef GPB_ENUM(MessageData_FieldNumber) {
  MessageData_FieldNumber_MessageId = 1,
  MessageData_FieldNumber_Content = 2,
  MessageData_FieldNumber_Param = 3,
  MessageData_FieldNumber_SendTime = 4,
  MessageData_FieldNumber_SourceId = 5,
  MessageData_FieldNumber_From = 6,
  MessageData_FieldNumber_MsgType = 7,
  MessageData_FieldNumber_To = 8,
};

@interface MessageData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *param;
/** Test to see if @c param has been set. */
@property(nonatomic, readwrite) BOOL hasParam;

@property(nonatomic, readwrite) int64_t sendTime;

@property(nonatomic, readwrite) BOOL hasSendTime;
@property(nonatomic, readwrite, copy, null_resettable) NSString *sourceId;
/** Test to see if @c sourceId has been set. */
@property(nonatomic, readwrite) BOOL hasSourceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *from;
/** Test to see if @c from has been set. */
@property(nonatomic, readwrite) BOOL hasFrom;

@property(nonatomic, readwrite) int32_t msgType;

@property(nonatomic, readwrite) BOOL hasMsgType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;
/** Test to see if @c to has been set. */
@property(nonatomic, readwrite) BOOL hasTo;

@end

#pragma mark - MessageACKResponse

typedef GPB_ENUM(MessageACKResponse_FieldNumber) {
  MessageACKResponse_FieldNumber_Success = 1,
  MessageACKResponse_FieldNumber_ErrCode = 2,
  MessageACKResponse_FieldNumber_Message = 3,
  MessageACKResponse_FieldNumber_SessionId = 4,
};

@interface MessageACKResponse : GPBMessage

@property(nonatomic, readwrite) int32_t success;

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite) int32_t errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@end

#pragma mark - MessageACKRequest

typedef GPB_ENUM(MessageACKRequest_FieldNumber) {
  MessageACKRequest_FieldNumber_MessageId = 1,
  MessageACKRequest_FieldNumber_SessionId = 2,
};

@interface MessageACKRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
