// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: balance.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BalanceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface BalanceRoot : GPBRootObject
@end

#pragma mark - BalanceProto

typedef GPB_ENUM(BalanceProto_FieldNumber) {
  BalanceProto_FieldNumber_AvailableBalance = 1,
  BalanceProto_FieldNumber_Balance = 2,
  BalanceProto_FieldNumber_Equity = 3,
  BalanceProto_FieldNumber_Margin = 4,
  BalanceProto_FieldNumber_MaintenanceMargin = 5,
  BalanceProto_FieldNumber_MarginRatio = 6,
  BalanceProto_FieldNumber_ProfitLoss = 7,
  BalanceProto_FieldNumber_Currencycode = 8,
  BalanceProto_FieldNumber_AvailableCashout = 9,
  BalanceProto_FieldNumber_Bonus = 10,
  BalanceProto_FieldNumber_OvernightFunding = 11,
  BalanceProto_FieldNumber_Credit = 12,
};

/**
 * 高频 balance发生变动的时候推送到客户端
 * {
 *  "availableBalance":36062.99,"availableCashout":36062.99,"balance":50201.69,
 *  "bonus":0,"credit":0,
 *  "currencyCode":"USD","equity":37081.69,
 *  "maintenanceMargin":509.350,"margin":1018.70,
 *  "marginRatio":36.4009,"overnightFunding":0.00,"profitOrLoss":-13120.00
 * }
 **/
@interface BalanceProto : GPBMessage

/** 可用余额 */
@property(nonatomic, readwrite) double availableBalance;

/** 余额 */
@property(nonatomic, readwrite) double balance;

/** 净值 */
@property(nonatomic, readwrite) double equity;

/** 占用保证金 */
@property(nonatomic, readwrite) double margin;

/** 维持保证金 */
@property(nonatomic, readwrite) double maintenanceMargin;

/** 风险率 */
@property(nonatomic, readwrite) double marginRatio;

/** 收益 */
@property(nonatomic, readwrite) double profitLoss;

/** 入金货币币种 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *currencycode;

/** 可用保证金 */
@property(nonatomic, readwrite) double availableCashout;

/** 佣金 */
@property(nonatomic, readwrite) double bonus;

/** 隔夜费 */
@property(nonatomic, readwrite) double overnightFunding;

/** 信用值 */
@property(nonatomic, readwrite) double credit;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
