// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notify_info.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - NotifyInfoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface NotifyInfoRoot : GPBRootObject
@end

#pragma mark - NotifyInfoProto

typedef GPB_ENUM(NotifyInfoProto_FieldNumber) {
  NotifyInfoProto_FieldNumber_Id_p = 1,
  NotifyInfoProto_FieldNumber_Title = 2,
  NotifyInfoProto_FieldNumber_Content = 3,
};

@interface NotifyInfoProto : GPBMessage

/** 消息id     用于客户的消息跳转 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 消息title  多语言title */
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/** 消息内容    多语言content */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
