// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_status.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "OrderStatus.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - OrderStatusRoot

@implementation OrderStatusRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - OrderStatusRoot_FileDescriptor

static GPBFileDescriptor *OrderStatusRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.mitrade.pbs"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - OrderStatusProto

@implementation OrderStatusProto

@dynamic symbol;
@dynamic orderId;
@dynamic type;
@dynamic status;
@dynamic quantity;
@dynamic price;
@dynamic orderTime;
@dynamic orderDirection;
@dynamic stopLoss;
@dynamic takeProfit;
@dynamic trailingStops;

typedef struct OrderStatusProto__storage_ {
  uint32_t _has_storage_[1];
  NSString *symbol;
  NSString *orderId;
  NSString *type;
  NSString *status;
  double quantity;
  double price;
  int64_t orderTime;
  double stopLoss;
  double takeProfit;
  double trailingStops;
} OrderStatusProto__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "symbol",
        .dataTypeSpecific.className = NULL,
        .number = OrderStatusProto_FieldNumber_Symbol,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(OrderStatusProto__storage_, symbol),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "orderId",
        .dataTypeSpecific.className = NULL,
        .number = OrderStatusProto_FieldNumber_OrderId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(OrderStatusProto__storage_, orderId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = OrderStatusProto_FieldNumber_Type,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(OrderStatusProto__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "status",
        .dataTypeSpecific.className = NULL,
        .number = OrderStatusProto_FieldNumber_Status,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(OrderStatusProto__storage_, status),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "quantity",
        .dataTypeSpecific.className = NULL,
        .number = OrderStatusProto_FieldNumber_Quantity,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(OrderStatusProto__storage_, quantity),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "price",
        .dataTypeSpecific.className = NULL,
        .number = OrderStatusProto_FieldNumber_Price,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(OrderStatusProto__storage_, price),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "orderTime",
        .dataTypeSpecific.className = NULL,
        .number = OrderStatusProto_FieldNumber_OrderTime,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(OrderStatusProto__storage_, orderTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "orderDirection",
        .dataTypeSpecific.className = NULL,
        .number = OrderStatusProto_FieldNumber_OrderDirection,
        .hasIndex = 7,
        .offset = 8,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "stopLoss",
        .dataTypeSpecific.className = NULL,
        .number = OrderStatusProto_FieldNumber_StopLoss,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(OrderStatusProto__storage_, stopLoss),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "takeProfit",
        .dataTypeSpecific.className = NULL,
        .number = OrderStatusProto_FieldNumber_TakeProfit,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(OrderStatusProto__storage_, takeProfit),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "trailingStops",
        .dataTypeSpecific.className = NULL,
        .number = OrderStatusProto_FieldNumber_TrailingStops,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(OrderStatusProto__storage_, trailingStops),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[OrderStatusProto class]
                                     rootClass:[OrderStatusRoot class]
                                          file:OrderStatusRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(OrderStatusProto__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\002\007\000\007\t\000\t\010\000\n\n\000\013\r\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
