// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_status.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - OrderStatusRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface OrderStatusRoot : GPBRootObject
@end

#pragma mark - OrderStatusProto

typedef GPB_ENUM(OrderStatusProto_FieldNumber) {
  OrderStatusProto_FieldNumber_Symbol = 1,
  OrderStatusProto_FieldNumber_OrderId = 2,
  OrderStatusProto_FieldNumber_Type = 3,
  OrderStatusProto_FieldNumber_Status = 4,
  OrderStatusProto_FieldNumber_Quantity = 5,
  OrderStatusProto_FieldNumber_Price = 6,
  OrderStatusProto_FieldNumber_OrderTime = 7,
  OrderStatusProto_FieldNumber_OrderDirection = 8,
  OrderStatusProto_FieldNumber_StopLoss = 9,
  OrderStatusProto_FieldNumber_TakeProfit = 10,
  OrderStatusProto_FieldNumber_TrailingStops = 11,
};

@interface OrderStatusProto : GPBMessage

/** 品种类型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

/** 订单号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

/** 类型 CANCEL(取消)  CLOSE(平仓) PARTIAL_CLOSE(部分平仓) CREATE(建仓) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/** 参考 CLOSED, PENDING, EXECUTED, CANCELLED */
@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

/** 交易手数 */
@property(nonatomic, readwrite) double quantity;

/** 成交价 */
@property(nonatomic, readwrite) double price;

/** 下单时间 */
@property(nonatomic, readwrite) int64_t orderTime;

/** false:BUY, true:SELL 和交易系统保持一致 */
@property(nonatomic, readwrite) BOOL orderDirection;

/** 止损价 */
@property(nonatomic, readwrite) double stopLoss;

/** 止盈价 */
@property(nonatomic, readwrite) double takeProfit;

/** 追踪止损价钱 */
@property(nonatomic, readwrite) double trailingStops;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
