// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: quotation_reminder.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "QuotationReminder.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - QuotationReminderRoot

@implementation QuotationReminderRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - QuotationReminderRoot_FileDescriptor

static GPBFileDescriptor *QuotationReminderRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.mitrade.pbs"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - QuotationReminderProto

@implementation QuotationReminderProto

@dynamic id_p;
@dynamic symbol;
@dynamic type;
@dynamic trigger;
@dynamic value;

typedef struct QuotationReminderProto__storage_ {
  uint32_t _has_storage_[1];
  NSString *id_p;
  NSString *symbol;
  double value;
} QuotationReminderProto__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = QuotationReminderProto_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(QuotationReminderProto__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "symbol",
        .dataTypeSpecific.className = NULL,
        .number = QuotationReminderProto_FieldNumber_Symbol,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(QuotationReminderProto__storage_, symbol),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = QuotationReminderProto_FieldNumber_Type,
        .hasIndex = 2,
        .offset = 3,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "trigger",
        .dataTypeSpecific.className = NULL,
        .number = QuotationReminderProto_FieldNumber_Trigger,
        .hasIndex = 4,
        .offset = 5,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "value",
        .dataTypeSpecific.className = NULL,
        .number = QuotationReminderProto_FieldNumber_Value,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(QuotationReminderProto__storage_, value),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[QuotationReminderProto class]
                                     rootClass:[QuotationReminderRoot class]
                                          file:QuotationReminderRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(QuotationReminderProto__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
