// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: quotation_reminder.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - QuotationReminderRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface QuotationReminderRoot : GPBRootObject
@end

#pragma mark - QuotationReminderProto

typedef GPB_ENUM(QuotationReminderProto_FieldNumber) {
  QuotationReminderProto_FieldNumber_Id_p = 1,
  QuotationReminderProto_FieldNumber_Symbol = 2,
  QuotationReminderProto_FieldNumber_Type = 3,
  QuotationReminderProto_FieldNumber_Trigger = 4,
  QuotationReminderProto_FieldNumber_Value = 5,
};

/**
 * 低频推送
 **/
@interface QuotationReminderProto : GPBMessage

/** "dealt_116166656417220001" 24B 鉴于低频推送。不再拆分字段 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 2B 参见SymbolEnum */
@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

/** 1B 类型 true 是买价，false 是卖价 */
@property(nonatomic, readwrite) BOOL type;

/** 1B true涨过 false跌过 */
@property(nonatomic, readwrite) BOOL trigger;

/** 8B 价钱 1731.51 */
@property(nonatomic, readwrite) double value;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
