// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Response.pbobjc.h"
 #import "Quotation.pbobjc.h"
 #import "QuotationReminder.pbobjc.h"
 #import "Balance.pbobjc.h"
 #import "TradePeriodStatus.pbobjc.h"
 #import "OrderStatus.pbobjc.h"
 #import "NotifyInfo.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdirect-ivar-access"

#pragma mark - ResponseRoot

@implementation ResponseRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - ResponseRoot_FileDescriptor

static GPBFileDescriptor *ResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.mitrade.pbs"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - ResponseProto

@implementation ResponseProto

@dynamic bodyOneOfCase;
@dynamic version;
@dynamic quotationProto;
@dynamic quotationReminderProto;
@dynamic balanceProto;
@dynamic orderStatusProto;
@dynamic tradePeriodStatusProto;
@dynamic notifyInfoProto;

typedef struct ResponseProto__storage_ {
  uint32_t _has_storage_[2];
  int32_t version;
  QuotationProto *quotationProto;
  QuotationReminderProto *quotationReminderProto;
  BalanceProto *balanceProto;
  OrderStatusProto *orderStatusProto;
  TradePeriodStatusProto *tradePeriodStatusProto;
  NotifyInfoProto *notifyInfoProto;
} ResponseProto__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "version",
        .dataTypeSpecific.className = NULL,
        .number = ResponseProto_FieldNumber_Version,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ResponseProto__storage_, version),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "quotationProto",
        .dataTypeSpecific.className = GPBStringifySymbol(QuotationProto),
        .number = ResponseProto_FieldNumber_QuotationProto,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(ResponseProto__storage_, quotationProto),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "quotationReminderProto",
        .dataTypeSpecific.className = GPBStringifySymbol(QuotationReminderProto),
        .number = ResponseProto_FieldNumber_QuotationReminderProto,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(ResponseProto__storage_, quotationReminderProto),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "balanceProto",
        .dataTypeSpecific.className = GPBStringifySymbol(BalanceProto),
        .number = ResponseProto_FieldNumber_BalanceProto,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(ResponseProto__storage_, balanceProto),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "orderStatusProto",
        .dataTypeSpecific.className = GPBStringifySymbol(OrderStatusProto),
        .number = ResponseProto_FieldNumber_OrderStatusProto,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(ResponseProto__storage_, orderStatusProto),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "tradePeriodStatusProto",
        .dataTypeSpecific.className = GPBStringifySymbol(TradePeriodStatusProto),
        .number = ResponseProto_FieldNumber_TradePeriodStatusProto,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(ResponseProto__storage_, tradePeriodStatusProto),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "notifyInfoProto",
        .dataTypeSpecific.className = GPBStringifySymbol(NotifyInfoProto),
        .number = ResponseProto_FieldNumber_NotifyInfoProto,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(ResponseProto__storage_, notifyInfoProto),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ResponseProto class]
                                     rootClass:[ResponseRoot class]
                                          file:ResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ResponseProto__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    static const char *oneofs[] = {
      "body",
    };
    [localDescriptor setupOneofs:oneofs
                           count:(uint32_t)(sizeof(oneofs) / sizeof(char*))
                   firstHasIndex:-1];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\006\002\016\000\003\026\000\004\014\000\005\020\000\006\026\000\007\017\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

void ResponseProto_ClearBodyOneOfCase(ResponseProto *message) {
  GPBDescriptor *descriptor = [message descriptor];
  GPBOneofDescriptor *oneof = [descriptor.oneofs objectAtIndex:0];
  GPBMaybeClearOneof(message, oneof, -1, 0);
}

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
