// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BalanceProto;
@class NotifyInfoProto;
@class OrderStatusProto;
@class QuotationProto;
@class QuotationReminderProto;
@class TradePeriodStatusProto;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ResponseRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ResponseRoot : GPBRootObject
@end

#pragma mark - ResponseProto

typedef GPB_ENUM(ResponseProto_FieldNumber) {
  ResponseProto_FieldNumber_Version = 1,
  ResponseProto_FieldNumber_QuotationProto = 2,
  ResponseProto_FieldNumber_QuotationReminderProto = 3,
  ResponseProto_FieldNumber_BalanceProto = 4,
  ResponseProto_FieldNumber_OrderStatusProto = 5,
  ResponseProto_FieldNumber_TradePeriodStatusProto = 6,
  ResponseProto_FieldNumber_NotifyInfoProto = 7,
};

typedef GPB_ENUM(ResponseProto_Body_OneOfCase) {
  ResponseProto_Body_OneOfCase_GPBUnsetOneOfCase = 0,
  ResponseProto_Body_OneOfCase_QuotationProto = 2,
  ResponseProto_Body_OneOfCase_QuotationReminderProto = 3,
  ResponseProto_Body_OneOfCase_BalanceProto = 4,
  ResponseProto_Body_OneOfCase_OrderStatusProto = 5,
  ResponseProto_Body_OneOfCase_TradePeriodStatusProto = 6,
  ResponseProto_Body_OneOfCase_NotifyInfoProto = 7,
};

@interface ResponseProto : GPBMessage

/** 版本控制,默认值是0.暂时不打算启用 */
@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readonly) ResponseProto_Body_OneOfCase bodyOneOfCase;

/** 报价 */
@property(nonatomic, readwrite, strong, null_resettable) QuotationProto *quotationProto;

/** 报价提醒 */
@property(nonatomic, readwrite, strong, null_resettable) QuotationReminderProto *quotationReminderProto;

/** 余额资产 */
@property(nonatomic, readwrite, strong, null_resettable) BalanceProto *balanceProto;

/** 订单状态变更通知 */
@property(nonatomic, readwrite, strong, null_resettable) OrderStatusProto *orderStatusProto;

/** 交易周期变更信息 */
@property(nonatomic, readwrite, strong, null_resettable) TradePeriodStatusProto *tradePeriodStatusProto;

/** 消息推送 */
@property(nonatomic, readwrite, strong, null_resettable) NotifyInfoProto *notifyInfoProto;

@end

/**
 * Clears whatever value was set for the oneof 'body'.
 **/
void ResponseProto_ClearBodyOneOfCase(ResponseProto *message);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
