// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_period_status.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TradePeriodStatusRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface TradePeriodStatusRoot : GPBRootObject
@end

#pragma mark - TradePeriodStatusProto

typedef GPB_ENUM(TradePeriodStatusProto_FieldNumber) {
  TradePeriodStatusProto_FieldNumber_Symbol = 1,
  TradePeriodStatusProto_FieldNumber_Type = 2,
  TradePeriodStatusProto_FieldNumber_CurrentStart = 3,
  TradePeriodStatusProto_FieldNumber_CurrentEnd = 4,
  TradePeriodStatusProto_FieldNumber_NextStart = 5,
  TradePeriodStatusProto_FieldNumber_NextEnd = 6,
  TradePeriodStatusProto_FieldNumber_Status = 7,
  TradePeriodStatusProto_FieldNumber_SubStatus = 8,
  TradePeriodStatusProto_FieldNumber_TradingSession1Array = 9,
  TradePeriodStatusProto_FieldNumber_TradingSession2Array = 10,
  TradePeriodStatusProto_FieldNumber_TradingSession3Array = 11,
  TradePeriodStatusProto_FieldNumber_TradingSession4Array = 12,
  TradePeriodStatusProto_FieldNumber_TradingSession5Array = 13,
  TradePeriodStatusProto_FieldNumber_TradingSession6Array = 14,
  TradePeriodStatusProto_FieldNumber_TradingSession7Array = 15,
};

/**
 * 低频推送
 **/
@interface TradePeriodStatusProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite) int64_t currentStart;

@property(nonatomic, readwrite) int64_t currentEnd;

@property(nonatomic, readwrite) int64_t nextStart;

@property(nonatomic, readwrite) int64_t nextEnd;

/** TradeStatusEnum */
@property(nonatomic, readwrite) int32_t status;

/** TradeSubStatusEnum */
@property(nonatomic, readwrite) int32_t subStatus;

/** ios和android不推送该值tradingSession?. webtrader里面tradingview图表里面用到 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tradingSession1Array;
/** The number of items in @c tradingSession1Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tradingSession1Array_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tradingSession2Array;
/** The number of items in @c tradingSession2Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tradingSession2Array_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tradingSession3Array;
/** The number of items in @c tradingSession3Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tradingSession3Array_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tradingSession4Array;
/** The number of items in @c tradingSession4Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tradingSession4Array_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tradingSession5Array;
/** The number of items in @c tradingSession5Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tradingSession5Array_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tradingSession6Array;
/** The number of items in @c tradingSession6Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tradingSession6Array_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tradingSession7Array;
/** The number of items in @c tradingSession7Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tradingSession7Array_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
