// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: quotation.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - QuotationRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface QuotationRoot : GPBRootObject
@end

#pragma mark - QuotationData

typedef GPB_ENUM(QuotationData_FieldNumber) {
  QuotationData_FieldNumber_Code = 1,
  QuotationData_FieldNumber_Name = 2,
  QuotationData_FieldNumber_Last = 3,
  QuotationData_FieldNumber_Open = 4,
  QuotationData_FieldNumber_High = 5,
  QuotationData_FieldNumber_Low = 6,
  QuotationData_FieldNumber_Lastclose = 7,
  QuotationData_FieldNumber_Lastsettlement = 8,
  QuotationData_FieldNumber_Volume = 9,
  QuotationData_FieldNumber_Excode = 10,
  QuotationData_FieldNumber_Exname = 11,
  QuotationData_FieldNumber_QuoteTime = 12,
  QuotationData_FieldNumber_Buy = 13,
  QuotationData_FieldNumber_Buyqty = 14,
  QuotationData_FieldNumber_Sell = 15,
  QuotationData_FieldNumber_Sellqty = 16,
  QuotationData_FieldNumber_Buy1 = 17,
  QuotationData_FieldNumber_Buy1Qty = 18,
  QuotationData_FieldNumber_Sell1 = 19,
  QuotationData_FieldNumber_Sell1Qty = 20,
  QuotationData_FieldNumber_Buy2 = 21,
  QuotationData_FieldNumber_Buy2Qty = 22,
  QuotationData_FieldNumber_Sell2 = 23,
  QuotationData_FieldNumber_Sell2Qty = 24,
  QuotationData_FieldNumber_Buy3 = 25,
  QuotationData_FieldNumber_Buy3Qty = 26,
  QuotationData_FieldNumber_Sell3 = 27,
  QuotationData_FieldNumber_Sell3Qty = 28,
  QuotationData_FieldNumber_Buy4 = 29,
  QuotationData_FieldNumber_Buy4Qty = 30,
  QuotationData_FieldNumber_Sell4 = 31,
  QuotationData_FieldNumber_Sell4Qty = 32,
  QuotationData_FieldNumber_Buy5 = 33,
  QuotationData_FieldNumber_Buy5Qty = 34,
  QuotationData_FieldNumber_Sell5 = 35,
  QuotationData_FieldNumber_Sell5Qty = 36,
  QuotationData_FieldNumber_Currentqty = 37,
  QuotationData_FieldNumber_Holdqty = 38,
  QuotationData_FieldNumber_IsTd = 39,
  QuotationData_FieldNumber_DecimalCount = 40,
  QuotationData_FieldNumber_Status = 41,
};

@interface QuotationData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *code;
/** Test to see if @c code has been set. */
@property(nonatomic, readwrite) BOOL hasCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite) float last;

@property(nonatomic, readwrite) BOOL hasLast;
@property(nonatomic, readwrite) float open;

@property(nonatomic, readwrite) BOOL hasOpen;
@property(nonatomic, readwrite) float high;

@property(nonatomic, readwrite) BOOL hasHigh;
@property(nonatomic, readwrite) float low;

@property(nonatomic, readwrite) BOOL hasLow;
@property(nonatomic, readwrite) float lastclose;

@property(nonatomic, readwrite) BOOL hasLastclose;
@property(nonatomic, readwrite) float lastsettlement;

@property(nonatomic, readwrite) BOOL hasLastsettlement;
@property(nonatomic, readwrite) int64_t volume;

@property(nonatomic, readwrite) BOOL hasVolume;
@property(nonatomic, readwrite, copy, null_resettable) NSString *excode;
/** Test to see if @c excode has been set. */
@property(nonatomic, readwrite) BOOL hasExcode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *exname;
/** Test to see if @c exname has been set. */
@property(nonatomic, readwrite) BOOL hasExname;

@property(nonatomic, readwrite) int64_t quoteTime;

@property(nonatomic, readwrite) BOOL hasQuoteTime;
@property(nonatomic, readwrite) float buy;

@property(nonatomic, readwrite) BOOL hasBuy;
@property(nonatomic, readwrite) int32_t buyqty;

@property(nonatomic, readwrite) BOOL hasBuyqty;
@property(nonatomic, readwrite) float sell;

@property(nonatomic, readwrite) BOOL hasSell;
@property(nonatomic, readwrite) int32_t sellqty;

@property(nonatomic, readwrite) BOOL hasSellqty;
@property(nonatomic, readwrite) float buy1;

@property(nonatomic, readwrite) BOOL hasBuy1;
@property(nonatomic, readwrite) int32_t buy1Qty;

@property(nonatomic, readwrite) BOOL hasBuy1Qty;
@property(nonatomic, readwrite) float sell1;

@property(nonatomic, readwrite) BOOL hasSell1;
@property(nonatomic, readwrite) int32_t sell1Qty;

@property(nonatomic, readwrite) BOOL hasSell1Qty;
@property(nonatomic, readwrite) float buy2;

@property(nonatomic, readwrite) BOOL hasBuy2;
@property(nonatomic, readwrite) int32_t buy2Qty;

@property(nonatomic, readwrite) BOOL hasBuy2Qty;
@property(nonatomic, readwrite) float sell2;

@property(nonatomic, readwrite) BOOL hasSell2;
@property(nonatomic, readwrite) int32_t sell2Qty;

@property(nonatomic, readwrite) BOOL hasSell2Qty;
@property(nonatomic, readwrite) float buy3;

@property(nonatomic, readwrite) BOOL hasBuy3;
@property(nonatomic, readwrite) int32_t buy3Qty;

@property(nonatomic, readwrite) BOOL hasBuy3Qty;
@property(nonatomic, readwrite) float sell3;

@property(nonatomic, readwrite) BOOL hasSell3;
@property(nonatomic, readwrite) int32_t sell3Qty;

@property(nonatomic, readwrite) BOOL hasSell3Qty;
@property(nonatomic, readwrite) float buy4;

@property(nonatomic, readwrite) BOOL hasBuy4;
@property(nonatomic, readwrite) int32_t buy4Qty;

@property(nonatomic, readwrite) BOOL hasBuy4Qty;
@property(nonatomic, readwrite) float sell4;

@property(nonatomic, readwrite) BOOL hasSell4;
@property(nonatomic, readwrite) int32_t sell4Qty;

@property(nonatomic, readwrite) BOOL hasSell4Qty;
@property(nonatomic, readwrite) float buy5;

@property(nonatomic, readwrite) BOOL hasBuy5;
@property(nonatomic, readwrite) int32_t buy5Qty;

@property(nonatomic, readwrite) BOOL hasBuy5Qty;
@property(nonatomic, readwrite) float sell5;

@property(nonatomic, readwrite) BOOL hasSell5;
@property(nonatomic, readwrite) int32_t sell5Qty;

@property(nonatomic, readwrite) BOOL hasSell5Qty;
@property(nonatomic, readwrite) int32_t currentqty;

@property(nonatomic, readwrite) BOOL hasCurrentqty;
@property(nonatomic, readwrite) int32_t holdqty;

@property(nonatomic, readwrite) BOOL hasHoldqty;
@property(nonatomic, readwrite) int32_t isTd;

@property(nonatomic, readwrite) BOOL hasIsTd;
@property(nonatomic, readwrite) int32_t decimalCount;

@property(nonatomic, readwrite) BOOL hasDecimalCount;
@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite) BOOL hasStatus;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
